# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: day-one
version: '0.0.0'
github: "githubuser/day-one"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: day-one is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  day-one:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - day-one
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  day-one-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - day-one
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  day-one-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - day-one
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
